version: '3.4'
services:
  db:
    platform: linux/amd64
    image: mysql:5.7 #using official mysql image from docker hub
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306"

  backend:
    platform: linux/arm64
    build:
      context: .
      dockerfile: backend-dev.Dockerfile
    ports:
      - "3001:3001"
    volumes:
      #the host repos are mapped to the container's repos
      - ./backend:/sekai
      #volume to cache gems
      - bundle:/bundle
    depends_on:
      - db
    stdin_open: true
    tty: true
    env_file: .env
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3001 -b '0.0.0.0'"

volumes:
  db_data:
    driver: local
  bundle:
    driver: local