version: 0.2

phases:
  pre_build:
    commands:
      - echo starting deployment buildspec
  build:
    commands:
      # - cd backend # Change to the repository directory
      - ls
      - cp staging.Dockerfile Dockerfile # Copy the content of stag.Dockerfile to Dockerfile 
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'
base-directory: backend
