version: 0.2

phases:
  pre_build:
    commands:
      - echo starting deployment buildspec
  build:
    commands:
      - echo building deployment buildspec
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  base-directory: backend
  files:
    - '**/*'